<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Billing.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Serilog" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Billing.Contracts\Billing.Contracts.csproj" />
    <ProjectReference Include="..\Billing.Domain\Billing.Domain.csproj" />
    <ProjectReference Include="..\Billing.Persistence\Billing.Persistence.csproj" />
    <ProjectReference Include="..\Billing.Shared\Billing.Shared.csproj" />
  </ItemGroup>

</Project>
