<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Billing.API</RootNamespace>
    <UserSecretsId>billing-api-secrets-2026</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.7.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Billing.Application\Billing.Application.csproj" />
    <ProjectReference Include="..\Billing.Contracts\Billing.Contracts.csproj" />
    <ProjectReference Include="..\Billing.Domain\Billing.Domain.csproj" />
    <ProjectReference Include="..\Billing.Identity\Billing.Identity.csproj" />
    <ProjectReference Include="..\Billing.Infrastructure\Billing.Infrastructure.csproj" />
    <ProjectReference Include="..\Billing.Persistence\Billing.Persistence.csproj" />
    <ProjectReference Include="..\Billing.Shared\Billing.Shared.csproj" />
  </ItemGroup>

</Project>
